# Generated by Django 2.0 on 2018-05-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('coupoun_code', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(max_length=2500)),
                ('status', models.CharField(max_length=10)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('imageUrl', models.URLField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catId', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('home_url', models.URLField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('affiliate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliate_token', models.CharField(blank=True, max_length=250, null=True)),
                ('logo_image', models.ImageField(null=True, upload_to='stores/')),
                ('aff_name', models.CharField(blank=True, max_length=128, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='parent_cats',
            field=models.ManyToManyField(related_name='stores', to='webapp.StoreCategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='store_cats',
            field=models.ManyToManyField(related_name='categories', to='webapp.Store'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Store'),
        ),
    ]
