# Generated by Django 2.0 on 2018-06-12 00:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_auto_20180612_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='users',
            field=models.ManyToManyField(related_name='favourite_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(related_name='favourite_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 7, 52, 38618)),
        ),
    ]
