# Generated by Django 2.0 on 2018-06-12 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180612_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 17, 43, 12, 699795)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='categories', to='webapp.Store'),
        ),
    ]
