# Generated by Django 2.0 on 2018-06-14 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180612_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='users',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 7, 57, 36, 5326)),
        ),
    ]
