# Generated by Django 2.0 on 2018-06-19 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20180614_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catId', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='store',
            name='parent_cats',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 23, 28, 29, 656625)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Category'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='stores', to='webapp.Category'),
        ),
    ]
