# Generated by Django 2.0 on 2018-06-19 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20180619_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreCategory',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 23, 29, 38, 653180)),
        ),
    ]
