# Generated by Django 2.0 on 2018-06-19 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180619_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 3, 51, 41, 856645)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webapp.Category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(to='webapp.Category'),
        ),
    ]
