# Generated by Django 2.0 on 2018-06-24 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180624_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 11, 24, 23, 148215)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='imageUrl',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='offerupdate',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 11, 24, 23, 132583)),
        ),
    ]
