# Generated by Django 2.0 on 2018-06-24 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20180624_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 12, 41, 3, 398044)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Category'),
        ),
        migrations.AlterField(
            model_name='offerupdate',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 12, 41, 3, 382420)),
        ),
    ]
